apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
stringData:
  JWT_SECRET: devopsShackSuperSecretKey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: nodejs-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "rds-secret"      
      initContainers:
        - name: wait-for-rds
          image: busybox:1.31
          command:
            - sh
            - -c
            - >
              echo "Waiting for RDS...";
              until nc -z "$DB_HOST" 3306; do
                sleep 2;
              done;
              echo "RDS is reachable."
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_HOST

        - name: wait-for-schema
          image: mysql:8
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB schema (users table)..."
              until mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -D $DB_NAME -e "SELECT 1 FROM users LIMIT 1;" >/dev/null 2>&1; do
                echo "Waiting for users table..."
                sleep 5
              done
              echo "Schema is ready!"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_USERNAME
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_PASSWORD
      containers:
        - name: backend
          image: adijaiswal/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_USERNAME
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_NAME
            - name: RESET_ADMIN_PASS
              value: "true"
              
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret-k8s
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
