apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
stringData:
  DB_PASSWORD: StrongPass123!
  JWT_SECRET: devopsShackSuperSecretKey
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  DB_USER: admin
  DB_NAME: crud_app
  RESET_ADMIN_PASS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-rds
          image: busybox:1.31
          command:
            - sh
            - -c
            - >
              echo "Waiting for RDS...";
              until nc -z "$DB_HOST" 3306; do
                sleep 2;
              done;
              echo "RDS is reachable."
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST

        - name: wait-for-schema
          image: mysql:8
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB schema (users table)..."
              until mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -D $DB_NAME -e "SELECT 1 FROM users LIMIT 1;" >/dev/null 2>&1; do
                echo "Waiting for users table..."
                sleep 5
              done
              echo "Schema is ready!"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
      containers:
        - name: backend
          image: adijaiswal/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: RESET_ADMIN_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RESET_ADMIN_PASS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
