apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: crud_app
  RESET_ADMIN_PASS: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "backend-role"

        # Secret path in Vault
        vault.hashicorp.com/agent-inject-secret-backend: "secret/data/backend"

        # Template to export env variables
        vault.hashicorp.com/agent-inject-template-backend: |
          {{- with secret "secret/data/backend" -}}
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end }}
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: adijaiswal/backend:latest
          
          # Load secrets before app starts
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Loading secrets from Vault..."
              . /vault/secrets/backend
              echo "Starting backend..."
              node app.js

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME

            - name: RESET_ADMIN_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RESET_ADMIN_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000