apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secret
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "nodejs-rds-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_USERNAME
            objectAlias: DB_USERNAME
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: DB_PORT          
            objectAlias: DB_PORT
  secretObjects:
    - secretName: rds-secret-k8s
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: DB_PORT
          key: DB_PORT